apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-back
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-back
  template:
    metadata:
      labels:
        app: demo-back
    spec:
      containers:
        - name: back
          image: ghcr.io/organization-demo-task/demo-back
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: demo-back
spec:
  selector:
    app: demo-back
  ports:
    - port: 8000
      targetPort: 8000
