apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-front
  template:
    metadata:
      labels:
        app: demo-front
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: front
          image: ghcr.io/organization-demo-task/demo-front
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: demo-front
spec:
  selector:
    app: demo-front
  ports:
    - port: 80
      targetPort: 80
